// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf3e-Nza4ZCeCkLKNMCdVs_r_IwuapT1s',
    appId: '1:509124225523:web:d657f1e486f81bbee24a86',
    messagingSenderId: '509124225523',
    projectId: 'acl-exavation',
    authDomain: 'acl-exavation.firebaseapp.com',
    storageBucket: 'acl-exavation.firebasestorage.app',
    measurementId: 'G-RSJBECX2YW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHeRksP9eDhJPP2daDzIjRohuiuYXRXHs',
    appId: '1:509124225523:android:d4062708b1bd443ce24a86',
    messagingSenderId: '509124225523',
    projectId: 'acl-exavation',
    storageBucket: 'acl-exavation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnHYvEXOEi65vFQ9OWdpzo4s21fwtlVfg',
    appId: '1:509124225523:ios:50e6776f2f61cb56e24a86',
    messagingSenderId: '509124225523',
    projectId: 'acl-exavation',
    storageBucket: 'acl-exavation.firebasestorage.app',
    iosBundleId: 'com.example.aclExavationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnHYvEXOEi65vFQ9OWdpzo4s21fwtlVfg',
    appId: '1:509124225523:ios:50e6776f2f61cb56e24a86',
    messagingSenderId: '509124225523',
    projectId: 'acl-exavation',
    storageBucket: 'acl-exavation.firebasestorage.app',
    iosBundleId: 'com.example.aclExavationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf3e-Nza4ZCeCkLKNMCdVs_r_IwuapT1s',
    appId: '1:509124225523:web:acfd2e7133dbdb9ee24a86',
    messagingSenderId: '509124225523',
    projectId: 'acl-exavation',
    authDomain: 'acl-exavation.firebaseapp.com',
    storageBucket: 'acl-exavation.firebasestorage.app',
    measurementId: 'G-9BNMPBLD5X',
  );
}
